# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.cache/wt [current_project]
set_property parent.project_path C:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/work/vivado_work/PYNQ-master_2/boards/ip [current_project]
add_files C:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_btns_gpio_0/system_btns_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_btns_gpio_0/system_btns_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_btns_gpio_0/system_btns_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_fclk1_0/system_proc_sys_reset_fclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_fclk1_0/system_proc_sys_reset_fclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_fclk1_0/system_proc_sys_reset_fclk1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_fclk0_0/system_rst_processing_system7_0_fclk0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_fclk0_0/system_rst_processing_system7_0_fclk0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_fclk0_0/system_rst_processing_system7_0_fclk0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_system_interrupts_0/system_system_interrupts_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_system_interrupts_0/system_system_interrupts_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_system_interrupts_0/system_system_interrupts_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axi_vdma_0/system_axi_vdma_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axi_vdma_0/system_axi_vdma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axi_vdma_0/system_axi_vdma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axis_register_slice_0_0/system_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_color_convert_0/constraints/color_convert_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_vtc_in_0/system_vtc_in_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_vtc_in_0/system_vtc_in_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_pixel_pack_0/constraints/pixel_pack_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_color_convert_1/constraints/color_convert_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_vtc_out_0/system_vtc_out_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_vtc_out_0/system_vtc_out_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_pixel_unpack_0/constraints/pixel_unpack_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axi_apb_bridge_0_1/system_axi_apb_bridge_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_h264enc_with_axi_0_1_1/src/fifo_8_64_enc/fifo_8_64_enc/fifo_8_64_enc_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_h264enc_with_axi_0_1_1/src/fifo_8_64_enc/fifo_8_64_enc/fifo_8_64_enc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_h264enc_with_axi_0_1_1/src/fifo_64_64_enc/fifo_64_64_enc/fifo_64_64_enc_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_h264enc_with_axi_0_1_1/src/fifo_64_64_enc/fifo_64_64_enc/fifo_64_64_enc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2yuv_with_axi_0_0_1/src/fifo_16_64/fifo_16_64/fifo_16_64_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2yuv_with_axi_0_0_1/src/fifo_16_64/fifo_16_64/fifo_16_64.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2yuv_with_axi_0_0_1/src/fifo_8_64/fifo_8_64/fifo_8_64_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2yuv_with_axi_0_0_1/src/fifo_8_64/fifo_8_64/fifo_8_64.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2yuv_with_axi_0_0_1/src/fifo_64_32/fifo_64_32/fifo_64_32_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_rgb2yuv_with_axi_0_0_1/src/fifo_64_32/fifo_64_32/fifo_64_32.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_axi_apb_bridge_1_0/system_axi_apb_bridge_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_5/system_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_6/system_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_cc_1/system_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_cc_1/system_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_cc_2/system_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_cc_2/system_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_cc_3/system_auto_cc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_cc_3/system_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_7/system_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_auto_pc_8/system_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib C:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/hdl/system_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files C:/work/vivado_work/PYNQ-master_2/boards/Pynq-Z1/base/base/base.srcs/constrs_1/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
